### ISSUE TITLE
Resolve RIC in Outcomes

### ISSUE THREAD

**Issue by RPanczak** [RPanczak/IeDEA_data_quality#4]
There are `NA`s in the results of Outcomes in the new data. 
Should that be directly replaced to RIC?
Are there any better tricks to handle that?

**Comment by RPanczak** [comment]
Currently `RIC` outcome is missing when dealing with data in the new format (ie using `tblLTFU` datset not `PAT`)

This causes the final graph in the report to look tad bad

![image](https://user-images.githubusercontent.com/31648642/108059651-1cf13400-7056-11eb-9533-d5b1aada2ec5.png){ width=50% height=50% }

One solution, quite naive probably is to replace `NA`s to `RIC`. 
More conservative is to perhaps use info from `l_alive_d` variable?
Full blown alternative would be to use more information from other tables to construct it.

What would you recommend @YRuffieux?

**Comment by YRuffieux** [comment]
I think changing the NA's to RIC (or equivantly, setting the outcome to RIC if `is.na(l_alive_d)`) is the best we can do. I really don't think we should shart making our own in-house definitions of RIC, or at least we'd have to figure out how they determine someone is RIC (`outcome==20`) in the PAT table and try to replicate it here. Maybe Cam Ha can tell us when she's less busy :)

Also, the fact that as opposed to the old dataset, the new dataset doesn't have a clear way of determining whether someone is RIC, might be of interest in and of itself.

**Comment by YRuffieux** [comment]
Another (lazy) option would be just to skip that particular graph in the case where we are comparing PAT to tblLTFU.
